/* oxlint-disable eslint-plugin-import/no-unassigned-import */
import '@a/ui/components/tooltip'
import '@a/ui/components/toggle-group'
import '@a/ui/components/toggle'
import '@a/ui/components/textarea'
import '@a/ui/components/tabs'
import '@a/ui/components/switch'
import '@a/ui/components/spinner'
import '@a/ui/components/sonner'
import '@a/ui/components/slider'
import '@a/ui/components/skeleton'
import '@a/ui/components/separator'
import '@a/ui/components/scroll-area'
import '@a/ui/components/resizable'
import '@a/ui/components/radio-group'
import '@a/ui/components/native-select'
import '@a/ui/components/label'
import '@a/ui/components/kbd'
import '@a/ui/components/input-otp'
import '@a/ui/components/input'
import '@a/ui/components/hover-card'
import '@a/ui/components/collapsible'
import '@a/ui/components/checkbox'
import '@a/ui/components/calendar'
import '@a/ui/components/button'
import '@a/ui/components/badge'
import '@a/ui/components/aspect-ratio'
import '@a/ui/components/alert'
import '@a/ui/components/accordion'
const Page = () => <p>ok</p>
export default Page
export const dynamic = 'force-dynamic'
